const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const saved=(()=>{try{return JSON.parse(localStorage.getItem('comp7906-progress')||'[]')}catch{return []}})();
const completed=new Set(Array.isArray(saved)?saved:[]);
function updateProgress(){ $('#progress-label').textContent=`已学 ${completed.size} / ${chapters.length} 章`; $$('.mark').forEach(b=>{b.textContent=completed.has(+b.dataset.chapter)?'已完成 · 再读本章':'标记本章已学完';b.setAttribute('aria-pressed',completed.has(+b.dataset.chapter))});try{localStorage.setItem('comp7906-progress',JSON.stringify([...completed]))}catch{}}
function render(){
 $('#sidebar-nav').innerHTML=chapters.map(c=>`<a class="chapter-link" href="#chapter-${c.no}"><span class="num">${String(c.no).padStart(2,'0')}</span><span>${c.title}</span></a>`).join('')+`<a class="chapter-link" href="#practice"><span class="num">练</span><span>配套原题训练</span></a><a class="chapter-link" href="#materials"><span class="num">读</span><span>资料与覆盖范围</span></a><a class="chapter-link" href="#selftest"><span class="num">08</span><span>整课自测</span></a><a class="chapter-link" href="#glossary"><span class="num">09</span><span>中英术语速查</span></a>`;
 $('#chapters').innerHTML=chapters.map(c=>`<section class="chapter" id="chapter-${c.no}" aria-labelledby="chapter-title-${c.no}"><header class="chapter-header"><div class="chapter-meta">LECTURE ${String(c.no).padStart(2,'0')} · ${c.en}</div><h2 id="chapter-title-${c.no}">${c.title}</h2><p>${c.intro}</p><div class="unit-index">${c.units.map((u,i)=>`<a href="#unit-${c.no}-${i}">${u.title}</a>`).join('')}</div></header>${c.units.map((u,i)=>`<article class="unit" id="unit-${c.no}-${i}"><div class="unit-title"><div><h3>${c.no}.${i+1} ${u.title}</h3><div class="en">${u.en}</div></div></div><div class="source">对应课件：${u.source||'Lecture '+c.no} · 第 ${u.pages} 页</div><div class="three"><div class="explain"><h4>是什么</h4><p>${u.what}</p></div><div class="explain"><h4>为什么</h4><p>${u.why}</p></div><div class="explain"><h4>怎么算 / 用</h4><p>${u.how}</p></div></div><aside class="analogy"><b>通俗理解</b>${u.analogy}</aside>${u.formula?`<div class="formula">${escapeHTML(u.formula)}</div>`:''}${u.foundation?`<details><summary>零基础补充：位、字节、十六进制与异或</summary><div class="mini-prereq"></div></details>`:""}<div class="lab" data-chapter="${c.no}" data-unit="${i}"><div class="lab-label">动手验证 · ${u.demo?.label||'互动实验'}</div><div class="lab-body"></div></div></article>`).join('')}<aside class="summary"><h3>本章小结</h3><ul>${c.summary.map(s=>`<li>${s}</li>`).join('')}</ul><button class="mark" data-chapter="${c.no}">标记本章已学完</button></aside></section>`).join('');
 $$('.lab').forEach(el=>mountDemo($('.lab-body',el),chapters[+el.dataset.chapter-1].units[+el.dataset.unit].demo));
 $$('.mini-prereq').forEach(mountFoundation);
 $$('.mark').forEach(b=>b.onclick=()=>{const n=+b.dataset.chapter;completed.has(n)?completed.delete(n):completed.add(n);updateProgress()});updateProgress();
 renderPractice();renderMaterials();
 if(typeof quizQuestions!=='undefined')renderQuiz();if(typeof glossary!=='undefined')renderGlossary();
 const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){$$('.chapter-link').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))}},{rootMargin:'-12% 0px -70% 0px'});$$('section.chapter').forEach(s=>observer.observe(s));
 const introButtons=$$('#intro-lab button');introButtons.forEach(b=>b.onclick=()=>{introButtons.forEach(x=>x.classList.toggle('selected',x===b));$('#intro-result').textContent=b.dataset.explain});
 $('#download').onclick=()=>{const blob=new Blob(['<!DOCTYPE html>\n'+document.documentElement.outerHTML],{type:'text/html;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='COMP7906-网安互动学习.html';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)};
}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),2800)}
window.addEventListener('DOMContentLoaded',()=>{render();registerLearningTools()});

function registerLearningTools(){
 const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
 const registry=[{name:'read_course_structure',title:'查看课程章节',description:'Read the ordered chapter list and learning units.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object.');return chapters.map(c=>({chapter:c.no,title:c.title,units:c.units.length}))}},{name:'navigate_to_chapter',title:'打开学习章节',description:'Scroll the visible learning page to chapter 1 through 7.',inputSchema:{type:'object',properties:{chapter:{type:'integer',minimum:1,maximum:7}},required:['chapter'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).length!==1||!Number.isInteger(input.chapter)||input.chapter<1||input.chapter>7)throw Error('Expected chapter 1–7.');const target=$('#chapter-'+input.chapter);target.scrollIntoView({behavior:'instant'});return {chapter:input.chapter,title:chapters[input.chapter-1].title}}}];
 for(const tool of registry){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}
}
