// Independent numerical checks against standard vectors and Node crypto.
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),vm=require('node:vm'),c=require('./algorithms');
assert.equal(c.inv(28,51),31);assert.equal(c.inv(12,61),56);assert.equal(c.inv(122,391),125);assert.throws(()=>c.inv(2,6));
assert.equal(c.powmod(65,17,3233),2790);assert.equal(c.powmod(2790,2753,3233),65);
for(const s of ['', 'abc', '中文摘要验证', 'a'.repeat(1000)])assert.equal(c.sha256(s),crypto.createHash('sha256').update(s).digest('hex'));
assert.equal(Buffer.from(c.rc4([1,2,3,4,5],Array(16).fill(0)).cipher).toString('hex'),'b2396305f03dc027ccc3524a0a1118a8');
for(const length of [16,24,32])for(let i=0;i<100;i++){const key=Array.from({length},(_,n)=>(17*n+7*i)&255),p=Array.from({length:16},(_,n)=>(31*n+19*i)&255),engine=crypto.createCipheriv(`aes-${length*8}-ecb`,Buffer.from(key),null);engine.setAutoPadding(false);const expected=Buffer.concat([engine.update(Buffer.from(p)),engine.final()]),encrypted=c.aesEncrypt(p,key).cipher;assert.deepEqual(Buffer.from(encrypted),expected);assert.deepEqual(c.aesDecrypt(encrypted,key).plain,p)}
assert.equal(c.saes(0xa749,0x2d55).cipher,0xc349);
for(let i=0;i<200;i++){const p=(i*251+17)&65535,k=(i*223+33)&65535;assert.equal(c.saesDecrypt(c.saes(p,k).cipher,k).plain,p);for(const t of [1,2,4,8]){const bits=p.toString(2).padStart(16,'0'),z=c.cfbSegments(bits,i&255,7,t);assert.equal(c.cfbSegments(z.output,i&255,7,t,true).output,bits)}const x=i&255;assert.equal(c.exerciseFeistel(c.exerciseFeistel(x,i%16).value,i%16,true).value,x)}
assert.equal(c.exerciseFeistel(0x96,2,true).value,0x92);assert.deepEqual(c.hillCandidates([18,14],[4,3],[6,4],[3,18]),[[[12,11],[3,2]],[[25,11],[3,2]]]);assert.equal(c.polyDiv(c.polyMul(0x57,0x83),0x11b).r,0xc1);assert.equal(c.gfmul(0x57,0x83),0xc1);
const key=Buffer.from('133457799BBCDFF1','hex'),ks=c.desKeySchedule([...key].flatMap(x=>x.toString(2).padStart(8,'0').split('').map(Number))),hx=x=>BigInt('0b'+x.join('')).toString(16);assert.equal(hx(ks.trace[0].k),'1b02effc7072');assert.equal(hx(ks.trace[15].k),'cb3d8b0e17f5');
assert.deepEqual(c.ecMul(2,[5,1],2,17),[6,3]);assert.equal(c.ecMul(19,[5,1],2,17),null);
const ctx={};vm.createContext(ctx);for(const file of ['content.js','enrichment.js','demos.js','advanced-demos.js','quiz.js','practice.js','materials.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx,{filename:file});
vm.runInContext(`globalThis.stats={units:chapters.reduce((s,c)=>s+c.units.length,0),cases:practiceCases.length,checks:practiceCases.reduce((s,c)=>s+c.checks.length,0),glossary:glossary.length,quiz:quizQuestions.length,unknown:chapters.flatMap(c=>c.units).filter(u=>!['explore','practice','cia'].includes(u.demo.type)&&!demoFactories[u.demo.type]).map(u=>u.demo.type),blankGlossary:glossary.filter(x=>x.length<3).length,chapterUnits:chapters.map(c=>c.units.length)};`,ctx);
assert.equal(ctx.stats.units,88);assert.equal(ctx.stats.cases,20);assert.equal(ctx.stats.checks,43);assert.equal(ctx.stats.quiz,20);assert.equal(ctx.stats.blankGlossary,0);assert.deepEqual(Array.from(ctx.stats.unknown),[]);console.log('PASS: 300 AES encrypt/decrypt standard comparisons; 200 S-AES, 800 CFB, 200 Feistel round trips; independent DES/RC4/SHA/GF/Hill/EC vectors.');console.log(JSON.stringify(ctx.stats));
